### ISSUE TITLE
YAML configuration is not documented

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/bom#48]
#### What would you like to be added:

`bom` supports defining complex SBOMs through a YAML configuration file. However, the YAML file is not defined anywhere. An example of the configuration file taken from the [bom-installer README](https://github.com/puerco/bom-installer/blob/main/README.md):

```yaml
---
namespace: https://example.com/
license: Apache-2.0
name: myproject
creator:
    person: Author Name (email@example.com)
artifacts:
    - type: directory
      source: .
      gomodules: true
    - type: file
      source: bin/linux-binary
    - type: file
      source: bin/mac-binary
    - type: file
      source: bin/windows-binary.exe
    - type: image
      source: ghcr.io/myorg/myrepo/myimage:tag
      license: Apache-2.0
```

#### Why is this needed:

If we expect users to use the feature, we should document it somewhere :upside_down_face:
